Numpy is a python library. It is used to deal with numerous calculations and many other operations. Arithematic operations, logical operations and many more.
We can create array with help of numpy and perform statistical operations on this according to use. 

Installation

In [ ]:
pip install numpy

If python and jupyter extensions added will go to terminal and type the above command. This will install numpy library to the Visual Studio Code.

In [ ]:
import numpy as np          ## this command will import numpy library

Array Creation

In [1]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print (a) 

[0 1 2 3 4 5]


Above a numpy array is created and printed. Numpy array will store numaric values and many operation are performed on that

Arithematic operations


In [5]:
a = np.array([0,1,2,3,4,5])
b = np.array([6,7,8,9,10,11])

## addition of arrays 

add = a+b
add
## multiplication of arrays

multiply = a*b
multiply
## division of arrays

divide = a/b
divide
## subtraction of arrays
subtract = a-b
subtract


array([-6, -6, -6, -6, -6, -6])

Array Sorting: Here we can sort an unsorted array with simple command sort. all the numbers will be sorted to accending order by default.

In [6]:
import numpy as np

arr = np.array([23,76,33,2,32,9,45,678,3556,5,3,4,78,234,67,6])

sort = np.sort(arr)

sort

array([   2,    3,    4,    5,    6,    9,   23,   32,   33,   45,   67,
         76,   78,  234,  678, 3556])

Zero Array: This array will print all zeros in the array. It means that all the array elements will be zero. 


In [7]:
import numpy as np

zeroa = np.zeros(4)

zeroa

array([0., 0., 0., 0.])

One Array: This will print all the array with 1 elements.

In [8]:
import numpy as np

onea = np.ones(5)

onea

array([1., 1., 1., 1., 1.])