In [2]:
import numpy as np

nA = np.array([10,22,45,67,89,3,6])    ## numpy array
print(nA)

## we can applay arithematic operations on numpy array
## here are some

print(nA + 1)    ## adding
print(nA - 1)    ## subtracting
print(nA / 1)    ## divide

## numpy array can add itself as

print(nA + nA)   ## adding array to itself

[10 22 45 67 89  3  6]
[11 23 46 68 90  4  7]
[ 9 21 44 66 88  2  5]
[10. 22. 45. 67. 89.  3.  6.]
[ 20  44  90 134 178   6  12]
